apiVersion: v1
kind: Secret
metadata:
  name: loantrack-db-secret
  namespace: loantrack
type: Opaque
stringData:
  POSTGRES_DB: dummy-loantrack
  POSTGRES_USER: dummy-user
  POSTGRES_PASSWORD: dummy-password
  DB_USER: dummy-user
  DB_PASSWORD: dummy-password
